---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python_version: ["3.10"]
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install testing dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install molecule
          pip install docker
          pip install podman
          pip install --user "molecule[podman,lint]"
          pip install --user "molecule[docker,lint]"

      - name: "Run molecule tests"
        run: molecule test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: rhel-8
